namespace PharmaStock.Desktop.Services;

/// <summary>Every user-facing string in the app, keyed by "{Page}_{Element}".
/// Grouped by screen (matches Views/*.xaml file order) purely so a missing
/// translation is easy to spot by scanning the relevant section — the
/// dictionary itself is flat, there's no per-page namespacing at lookup time.</summary>
public static class AppStrings
{
    public static readonly Dictionary<string, (string Fr, string En)> Map = new()
    {
        // Common / shared across pages
        ["Common_Cancel"] = ("Annuler", "Cancel"),
        ["Common_OK"] = ("OK", "OK"),
        ["Common_UnexpectedError"] = ("Erreur inattendue", "Unexpected error"),
        ["Common_Error"] = ("Erreur", "Error"),
        ["Common_Back"] = ("Précédent", "Back"),
        ["Common_Next"] = ("Suivant", "Next"),
        ["Common_BackToPage"] = ("Retour", "Back"),

        // Stock (shared: StockReceivePage/StockAdjustPage)
        ["Stock_ProductNotFound"] = ("Produit introuvable.", "Product not found."),
        ["Stock_CannotDetermineLocation"] = ("Impossible de déterminer l'emplacement. Essayez de rouvrir cet écran.", "Couldn't determine the location. Try reopening this screen."),

        // Stock status (shared across PosPage/ProductCatalogPage etc.)
        ["StockStatus_OutOfStock"] = ("Rupture de stock", "Out of stock"),
        ["StockStatus_LowStock"] = ("Stock faible", "Low stock"),
        ["StockStatus_InStock"] = ("En stock", "In stock"),

        // Payment methods (Domain.Models.PaymentMethod)
        ["PaymentMethod_Cash"] = ("Espèces", "Cash"),
        ["PaymentMethod_MobileMoney"] = ("Mobile Money", "Mobile Money"),
        ["PaymentMethod_Credit"] = ("Crédit", "Credit"),
        ["PaymentMethod_StoreCredit"] = ("Crédit-magasin", "Store credit"),
        ["PaymentMethod_GiftCard"] = ("Carte-cadeau", "Gift card"),
        ["PaymentMethod_Split"] = ("Paiement fractionné", "Split payment"),

        // Staff roles (Domain.Models.UserRole)
        ["Role_Cashier"] = ("Caissier", "Cashier"),
        ["Role_CompanyAdmin"] = ("Administrateur", "Administrator"),
        ["Role_SuperAdmin"] = ("Super administrateur", "Super admin"),

        // AppShell — flyout menu titles
        ["Shell_Dashboard"] = ("Tableau de bord", "Dashboard"),
        ["Shell_Pos"] = ("Vente", "Sale"),
        ["Shell_Products"] = ("Produits", "Products"),
        ["Shell_Categories"] = ("Catégories", "Categories"),
        ["Shell_Archives"] = ("Archives", "Archives"),
        ["Shell_SalesHistory"] = ("Historique des ventes", "Sales history"),
        ["Shell_HeldSales"] = ("Ventes en attente", "Held sales"),
        ["Shell_Reports"] = ("Rapports", "Reports"),
        ["Shell_PurchaseOrders"] = ("Bons de commande", "Purchase orders"),
        ["Shell_Suppliers"] = ("Fournisseurs", "Suppliers"),
        ["Shell_CompanySettings"] = ("Mon entreprise", "My company"),
        ["Shell_PrinterSettings"] = ("Imprimante", "Printer"),
        ["Shell_CashRegister"] = ("Caisse", "Cash register"),
        ["Shell_SalesGroup"] = ("Point de vente", "Point of sale"),
        ["Shell_CatalogGroup"] = ("Catalogue", "Catalog"),
        ["Shell_PurchasingGroup"] = ("Achats", "Purchasing"),
        ["Shell_ManagementGroup"] = ("Gestion", "Management"),

        // DashboardPage
        ["Dashboard_Title"] = ("Tableau de bord", "Dashboard"),
        ["Dashboard_Welcome"] = ("Bienvenue, {0} — {1}", "Welcome, {0} — {1}"),
        ["Dashboard_RevenueToday"] = ("Revenu aujourd'hui", "Revenue today"),
        ["Dashboard_SalesToday"] = ("Ventes aujourd'hui", "Sales today"),
        ["Dashboard_Products"] = ("Produits", "Products"),
        ["Dashboard_LowStock"] = ("Stock faible", "Low stock"),
        ["Dashboard_OutOfStock"] = ("Rupture de stock", "Out of stock"),
        ["Dashboard_ExpiringSoon"] = ("Expire bientôt", "Expiring soon"),
        ["Dashboard_Expired"] = ("Expiré", "Expired"),
        ["Dashboard_Archived"] = ("Archivés", "Archived"),
        ["Dashboard_NegativeStock"] = ("Conflits de synchro", "Sync conflicts"),
        ["Dashboard_RecentSales"] = ("VENTES RÉCENTES", "RECENT SALES"),
        ["Dashboard_NoRecentSales"] = ("Aucune vente pour le moment.", "No sales yet."),
        ["Dashboard_NoItems"] = ("Aucun article", "No items"),

        // OnboardingPage
        ["Onboarding_Subtitle"] = ("Gestion des stocks et des ventes pour votre entreprise", "Stock and sales management for your business"),
        ["Onboarding_CreateCompany"] = ("Créer une entreprise", "Create a business"),
        ["Onboarding_JoinCompany"] = ("Rejoindre une entreprise", "Join a business"),
        ["Onboarding_Login"] = ("Se connecter", "Log in"),

        // LoginPage
        ["Login_Title"] = ("Connexion", "Log in"),
        ["Login_Subtitle"] = ("Utilisez votre numéro de téléphone et votre mot de passe.", "Use your phone number and password."),
        ["Login_PhoneLabel"] = ("NUMÉRO DE TÉLÉPHONE", "PHONE NUMBER"),
        ["Login_PasswordLabel"] = ("MOT DE PASSE", "PASSWORD"),
        ["Login_PasswordPlaceholder"] = ("Votre mot de passe", "Your password"),
        ["Login_Submit"] = ("Se connecter", "Log in"),
        ["Login_MissingFields"] = ("Entrez votre numéro de téléphone et votre mot de passe.", "Enter your phone number and password."),
        ["Login_InvalidCredentials"] = ("Numéro de téléphone ou mot de passe incorrect.", "Incorrect phone number or password."),
        ["Login_GenericError"] = ("Une erreur s'est produite : {0}", "An error occurred: {0}"),

        // CreateCompanyPage
        ["CreateCompany_Title"] = ("Créer une entreprise", "Create a business"),
        ["CreateCompany_Heading"] = ("Créez votre entreprise", "Create your business"),
        ["CreateCompany_Step1"] = ("Étape 1 sur 2 — Entreprise", "Step 1 of 2 — Business"),
        ["CreateCompany_Step2"] = ("Étape 2 sur 2 — Compte administrateur", "Step 2 of 2 — Admin account"),
        ["CreateCompany_CompanySection"] = ("ENTREPRISE", "BUSINESS"),
        ["CreateCompany_NameLabel"] = ("NOM", "NAME"),
        ["CreateCompany_DescriptionLabel"] = ("DESCRIPTION (FACULTATIF)", "DESCRIPTION (OPTIONAL)"),
        ["CreateCompany_DescriptionPlaceholder"] = ("Une courte description", "A short description"),
        ["CreateCompany_CurrencyLabel"] = ("DEVISE", "CURRENCY"),
        ["CreateCompany_NamePlaceholder"] = ("ex. Ma Boutique", "e.g. My Shop"),
        ["CreateCompany_AdminSection"] = ("VOTRE COMPTE ADMINISTRATEUR", "YOUR ADMIN ACCOUNT"),
        ["CreateCompany_AdminNameLabel"] = ("VOTRE NOM", "YOUR NAME"),
        ["CreateCompany_AdminPasswordPlaceholder"] = ("Min. 6 caractères", "Min. 6 characters"),
        ["CreateCompany_Submit"] = ("Créer", "Create"),
        ["CreateCompany_NameRequired"] = ("Le nom de l'entreprise est requis.", "The business name is required."),
        ["CreateCompany_RequiredFields"] = ("Veuillez remplir tous les champs obligatoires.", "Please fill in all required fields."),

        // JoinCompanyPage
        ["JoinCompany_Title"] = ("Rejoindre une entreprise", "Join a business"),
        ["JoinCompany_Heading"] = ("Rejoignez votre entreprise", "Join your business"),
        ["JoinCompany_Subtitle"] = ("Entrez le code fourni par votre administrateur.", "Enter the code provided by your admin."),
        ["JoinCompany_CodeLabel"] = ("CODE DE L'ENTREPRISE", "BUSINESS CODE"),
        ["JoinCompany_Find"] = ("Rechercher", "Search"),
        ["JoinCompany_Continue"] = ("Continuer", "Continue"),
        ["JoinCompany_MissingCode"] = ("Entrez d'abord le code de l'entreprise.", "Enter the business code first."),
        ["JoinCompany_Found"] = ("Trouvé : {0}", "Found: {0}"),

        // PosPage
        ["Pos_Title"] = ("Vente", "Sale"),
        ["Pos_BarcodePlaceholder"] = ("Code-barres, puis Entrée", "Barcode, then Enter"),
        ["Pos_ScanButton"] = ("Scanner", "Scan"),
        ["Pos_SearchPlaceholder"] = ("Rechercher un produit", "Search for a product"),
        ["Pos_Cart"] = ("PANIER", "CART"),
        ["Pos_EmptyCart"] = ("Le panier est vide — scannez ou recherchez un produit pour commencer.", "The cart is empty — scan or search for a product to get started."),
        ["Pos_PaymentMethod"] = ("MODE DE PAIEMENT", "PAYMENT METHOD"),
        ["Pos_Cash"] = ("Espèces", "Cash"),
        ["Pos_MobileMoney"] = ("Mobile Money", "Mobile Money"),
        ["Pos_Split"] = ("Partagé", "Split"),
        ["Pos_SplitCashAmountPlaceholder"] = ("Montant en espèces", "Cash amount"),
        ["Pos_SplitMobileMoneyAmountPlaceholder"] = ("Montant Mobile Money", "Mobile Money amount"),
        ["Pos_SplitRemaining"] = ("Reste à répartir : {0}", "Remaining to allocate: {0}"),
        ["Pos_SplitMismatch"] = ("Le fractionnement doit totaliser {0}.", "The split must total {0}."),
        ["Pos_TenderedLabel"] = ("MONTANT REÇU (FACULTATIF)", "AMOUNT RECEIVED (OPTIONAL)"),
        ["Pos_TenderedPlaceholder"] = ("Montant reçu du client", "Amount received from customer"),
        ["Pos_ChangeDue"] = ("Monnaie à rendre : {0}", "Change due: {0}"),
        ["Pos_TenderedInsufficient"] = ("Le montant reçu est inférieur au montant dû en espèces.", "The amount received is less than the amount due in cash."),
        ["Pos_Total"] = ("Total", "Total"),
        ["Pos_Checkout"] = ("Encaisser", "Check out"),
        ["Pos_NoLocation"] = ("Aucun emplacement n'est configuré pour cette entreprise.", "No location is configured for this business."),
        ["Pos_BarcodeNotFound"] = ("Aucun produit trouvé pour le code-barres « {0} ».", "No product found for barcode \"{0}\"."),
        ["Pos_Unit"] = ("unité", "unit"),
        ["Pos_UnitCapitalized"] = ("Unité", "Unit"),
        ["Pos_CannotDetermineLocation"] = ("Impossible de déterminer l'emplacement pour cette vente. Essayez de rouvrir cet écran.", "Couldn't determine the location for this sale. Try reopening this screen."),
        ["Pos_SaleComplete"] = ("Vente terminée", "Sale complete"),
        ["Pos_SaleTotal"] = ("Total : {0}", "Total: {0}"),
        ["Pos_PrintAction"] = ("Imprimer", "Print"),
        ["Pos_ReceiptUnitLine"] = ("{0} unité(s) × {1}", "{0} unit(s) × {1}"),
        ["Pos_HoldAction"] = ("Mettre en attente", "Hold"),
        ["Pos_ResumeAction"] = ("Reprendre", "Resume"),
        ["Pos_HoldSuccess"] = ("Vente mise en attente.", "Sale put on hold."),
        ["Pos_CartNotEmptyForResume"] = ("Videz le panier actuel avant de reprendre une vente en attente.", "Empty the current cart before resuming a held sale."),

        // HeldSalesPage — resume/discard a parked cart (Section 18.1)
        ["HeldSales_Title"] = ("Ventes en attente", "Held sales"),
        ["HeldSales_Empty"] = ("Aucune vente en attente.", "No held sales."),
        ["HeldSales_RowSubtitle"] = ("{0} · {1} article(s) · {2}", "{0} · {1} item(s) · {2}"),
        ["HeldSales_DeleteTitle"] = ("Supprimer la vente en attente", "Delete held sale"),
        ["HeldSales_DeleteMessage"] = ("Supprimer cette vente en attente ? Le panier sera perdu définitivement.", "Delete this held sale? Its cart will be permanently lost."),
        ["HeldSales_Delete"] = ("Supprimer", "Delete"),

        // HeldSalesHistoryPage — browse/filter/export every held sale across
        // all locations (management view; distinct from HeldSalesPage, the
        // POS's own single-location "Reprendre" picker)
        ["HeldSalesHistory_Empty"] = ("Aucune vente en attente sur cette période.", "No held sales in this period."),
        ["HeldSalesHistory_RowSubtitle"] = ("{0} · {1} · {2} article(s) · {3}", "{0} · {1} · {2} item(s) · {3}"),
        ["HeldSalesHistory_Export"] = ("Exporter (Excel)", "Export (Excel)"),
        ["HeldSalesHistory_ExportEmpty"] = ("Aucune donnée à exporter pour cette période.", "No data to export for this period."),
        ["HeldSalesHistory_CsvDate"] = ("Date", "Date"),
        ["HeldSalesHistory_CsvLocation"] = ("Emplacement", "Location"),
        ["HeldSalesHistory_CsvCashier"] = ("Caissier", "Cashier"),
        ["HeldSalesHistory_CsvItems"] = ("Articles", "Items"),
        ["HeldSalesHistory_CsvTotal"] = ("Total", "Total"),

        // ReportsPage — Section 14
        ["Reports_Title"] = ("Rapports", "Reports"),
        ["Reports_Revenue"] = ("Revenu", "Revenue"),
        ["Reports_Profit"] = ("Profit", "Profit"),
        ["Reports_SalesCount"] = ("Ventes", "Sales"),
        ["Reports_AverageSale"] = ("Vente moyenne", "Average sale"),
        ["Reports_DailyBreakdown"] = ("Ventes par jour", "Sales by day"),
        ["Reports_DailyBreakdownEmpty"] = ("Aucune vente sur cette période.", "No sales in this period."),
        ["Reports_DailyRowSubtitle"] = ("{0} vente(s)", "{0} sale(s)"),
        ["Reports_TopProducts"] = ("Produits les plus vendus", "Top-selling products"),
        ["Reports_TopProductsEmpty"] = ("Aucun produit vendu sur cette période.", "No products sold in this period."),
        ["Reports_TopProductRowSubtitle"] = ("{0} vendu(s) · {1} de profit", "{0} sold · {1} profit"),
        ["Reports_Export"] = ("Exporter (Excel)", "Export (Excel)"),
        ["Reports_ExportEmpty"] = ("Aucune donnée à exporter pour cette période.", "No data to export for this period."),
        ["Reports_CsvDate"] = ("Date", "Date"),
        ["Reports_CsvRevenue"] = ("Revenu", "Revenue"),
        ["Reports_CsvSalesCount"] = ("Ventes", "Sales"),
        ["Reports_CsvProduct"] = ("Produit", "Product"),
        ["Reports_CsvQuantity"] = ("Quantité", "Quantity"),
        ["Reports_CsvProfit"] = ("Profit", "Profit"),

        // Shared by every .xlsx export (Rapports, Ventes en attente) — the
        // subtitle banner row and the totals row label.
        ["Export_Total"] = ("Total", "Total"),
        ["Export_AllDates"] = ("Toutes les dates", "All dates"),
        ["Export_DateRange"] = ("{0} au {1}", "{0} to {1}"),
        ["Export_GeneratedOn"] = ("Généré le {0}", "Generated on {0}"),

        // PurchaseOrdersListPage / PurchaseOrderCreatePage / PurchaseOrderDetailPage / ReceivePurchaseOrderLinePage — Section 3.4
        ["PurchaseOrder_New"] = ("Nouvelle commande", "New purchase order"),
        ["PurchaseOrder_Empty"] = ("Aucune commande sur cette période.", "No purchase orders in this period."),
        ["PurchaseOrder_StatusPending"] = ("En attente", "Pending"),
        ["PurchaseOrder_StatusPartial"] = ("Partielle", "Partial"),
        ["PurchaseOrder_StatusReceived"] = ("Reçue", "Received"),
        ["PurchaseOrder_StatusCancelled"] = ("Annulée", "Cancelled"),
        ["PurchaseOrder_RowSubtitle"] = ("{0} · {1} · {2} ligne(s) · {3}", "{0} · {1} · {2} line(s) · {3}"),
        ["PurchaseOrder_SupplierLabel"] = ("Fournisseur", "Supplier"),
        ["PurchaseOrder_SupplierPlaceholder"] = ("Choisir un fournisseur", "Choose a supplier"),
        ["PurchaseOrder_NotesLabel"] = ("Notes (facultatif)", "Notes (optional)"),
        ["PurchaseOrder_NotesPlaceholder"] = ("ex. Réapprovisionnement mensuel", "e.g. Monthly restock"),
        ["PurchaseOrder_AddProducts"] = ("Ajouter des produits", "Add products"),
        ["PurchaseOrder_Lines"] = ("Lignes de commande", "Order lines"),
        ["PurchaseOrder_NoLines"] = ("Recherchez un produit ci-dessus pour l'ajouter à la commande.", "Search for a product above to add it to the order."),
        ["PurchaseOrder_QuantityLabel"] = ("Qté", "Qty"),
        ["PurchaseOrder_UnitCostLabel"] = ("Coût unit.", "Unit cost"),
        ["PurchaseOrder_Submit"] = ("Créer la commande", "Create order"),
        ["PurchaseOrder_DetailTitle"] = ("Détail de la commande", "Purchase order detail"),
        ["PurchaseOrder_HeaderSubtitle"] = ("{0} — {1}", "{0} — {1}"),
        ["PurchaseOrder_LineSubtitle"] = ("Reçu {0} / {1} · {2} / unité", "Received {0} / {1} · {2} / unit"),
        ["PurchaseOrder_ReceiveAction"] = ("Recevoir", "Receive"),
        ["PurchaseOrder_ReceiveTitle"] = ("Réceptionner", "Receive delivery"),
        ["PurchaseOrder_ReceiveConfirm"] = ("Confirmer la réception", "Confirm receipt"),
        ["PurchaseOrder_RemainingSubtitle"] = ("{0} restant(s) sur {1} commandé(s)", "{0} remaining out of {1} ordered"),
        ["PurchaseOrder_QuantityReceivedLabel"] = ("Quantité reçue", "Quantity received"),
        ["PurchaseOrder_InvalidQuantity"] = ("La quantité doit être comprise entre 1 et {0}.", "Quantity must be between 1 and {0}."),
        ["PurchaseOrder_CancelOrder"] = ("Annuler la commande", "Cancel order"),
        ["PurchaseOrder_CancelTitle"] = ("Annuler la commande", "Cancel order"),
        ["PurchaseOrder_CancelMessage"] = ("Annuler cette commande ? Cette action est irréversible.", "Cancel this order? This cannot be undone."),
        ["PurchaseOrder_CancelConfirm"] = ("Annuler la commande", "Cancel order"),
        ["PurchaseOrder_SupplierFilterAll"] = ("Tous les fournisseurs", "All suppliers"),
        ["PurchaseOrder_RestockSuggestions"] = ("Produits à réapprovisionner", "Products to restock"),
        ["PurchaseOrder_NoRestockSuggestions"] = ("Aucun produit de ce fournisseur n'est en rupture ou stock faible.", "No products from this supplier are low or out of stock."),
        ["PurchaseOrder_RestockSuggestionSubtitle"] = ("Stock {0} / seuil {1} · suggéré {2}", "Stock {0} / threshold {1} · suggested {2}"),
        ["PurchaseOrder_Share"] = ("Partager", "Share"),
        ["PurchaseOrder_ShareHeader"] = ("Bon de commande — {0}", "Purchase order — {0}"),
        ["PurchaseOrder_ShareDate"] = ("Date : {0}", "Date: {0}"),
        ["PurchaseOrder_ShareLine"] = ("• {0} × {1} — {2} / unité", "• {0} × {1} — {2} / unit"),
        ["PurchaseOrder_ShareTotal"] = ("Total : {0}", "Total: {0}"),
        ["PurchaseOrder_ShareNotes"] = ("Notes : {0}", "Notes: {0}"),

        ["SupplierPicker_Title"] = ("Choisir un fournisseur", "Choose a supplier"),
        ["SupplierPicker_SearchPlaceholder"] = ("Rechercher un fournisseur", "Search suppliers"),
        ["SupplierPicker_New"] = ("Nouveau fournisseur", "New supplier"),
        ["SupplierPicker_NoResults"] = ("Aucun fournisseur trouvé.", "No suppliers found."),
        ["SupplierPicker_NewTitle"] = ("Nouveau fournisseur", "New supplier"),
        ["SupplierPicker_NamePrompt"] = ("Nom du fournisseur", "Supplier name"),

        // SupplierManagementPage / SupplierEditPage — full CRUD
        ["SupplierManagement_Empty"] = ("Aucun fournisseur enregistré.", "No suppliers registered."),
        ["SupplierManagement_DeleteTitle"] = ("Supprimer le fournisseur", "Delete supplier"),
        ["SupplierManagement_DeleteMessage"] = ("Supprimer « {0} » ? Cette action est irréversible.", "Delete \"{0}\"? This cannot be undone."),
        ["SupplierManagement_Delete"] = ("Supprimer", "Delete"),
        ["SupplierEdit_Title"] = ("Fournisseur", "Supplier"),
        ["SupplierEdit_TitleNew"] = ("Nouveau fournisseur", "New supplier"),
        ["SupplierEdit_TitleEdit"] = ("Modifier le fournisseur", "Edit supplier"),
        ["SupplierEdit_NameLabel"] = ("Nom", "Name"),
        ["SupplierEdit_NamePlaceholder"] = ("ex. Labo Cameroun SARL", "e.g. Labo Cameroun SARL"),
        ["SupplierEdit_PhoneLabel"] = ("Téléphone (facultatif)", "Phone (optional)"),
        ["SupplierEdit_EmailLabel"] = ("Email (facultatif)", "Email (optional)"),
        ["SupplierEdit_Save"] = ("Enregistrer", "Save"),
        ["SupplierEdit_NameRequired"] = ("Le nom du fournisseur est requis.", "Supplier name is required."),

        // CompanySettingsPage — "Gérer mon entreprise"
        ["CompanySettings_Title"] = ("Mon entreprise", "My company"),
        ["CompanySettings_NameLabel"] = ("Nom de l'entreprise", "Company name"),
        ["CompanySettings_NamePlaceholder"] = ("ex. Pharmacie du Centre", "e.g. Pharmacie du Centre"),
        ["CompanySettings_DescriptionLabel"] = ("Description (facultatif)", "Description (optional)"),
        ["CompanySettings_DescriptionPlaceholder"] = ("Brève description de l'entreprise", "Brief company description"),
        ["CompanySettings_CurrencyLabel"] = ("Devise", "Currency"),
        ["CompanySettings_TaxRateLabel"] = ("Taux de TVA par défaut (%)", "Default VAT rate (%)"),
        ["CompanySettings_InviteCodeLabel"] = ("Code d'invitation", "Invite code"),
        ["CompanySettings_InviteCodeHint"] = ("Partagez ce code pour que d'autres appareils rejoignent votre entreprise.", "Share this code so other devices can join your company."),
        ["CompanySettings_ShareInvite"] = ("Partager l'invitation", "Share invite"),
        ["CompanySettings_ShareInviteTitle"] = ("Invitation PharmaStock", "PharmaStock invitation"),
        ["CompanySettings_ShareInviteText"] = ("Rejoignez {0} sur PharmaStock !\n\n1. Installez l'application PharmaStock.\n2. Ouvrez-la et choisissez « Rejoindre une entreprise ».\n3. Entrez ce code d'invitation : {1}", "Join {0} on PharmaStock!\n\n1. Install the PharmaStock app.\n2. Open it and choose \"Join a company\".\n3. Enter this invite code: {1}"),
        ["CompanySettings_Save"] = ("Enregistrer", "Save"),
        ["CompanySettings_NameRequired"] = ("Le nom de l'entreprise est requis.", "Company name is required."),
        ["CompanySettings_Saved"] = ("Informations de l'entreprise mises à jour.", "Company details updated."),

        // Printer-related alerts (shared across PosPage/SaleDetailPage)
        ["Printer_NoneConfiguredTitle"] = ("Aucune imprimante", "No printer"),
        ["Printer_NoneConfiguredMessage"] = ("Configurez d'abord une imprimante dans le menu Imprimante.", "Set up a printer first from the Printer menu."),
        ["Printer_Configure"] = ("Configurer", "Configure"),
        ["Printer_PrintError"] = ("Erreur d'impression", "Print error"),
        ["Printer_PageTitle"] = ("Imprimante de tickets", "Receipt printer"),
        ["Printer_NoneSelected"] = ("Aucune imprimante sélectionnée.", "No printer selected."),
        ["Printer_CurrentPrinter"] = ("Imprimante actuelle : {0} ({1})", "Current printer: {0} ({1})"),
        ["Printer_AvailableDevices"] = ("APPAREILS DISPONIBLES", "AVAILABLE DEVICES"),
        ["Printer_NoDevicesFound"] = ("Aucun appareil trouvé. Pour le Bluetooth : activez-le si besoin (une demande peut apparaître automatiquement), appairez l'imprimante via « Pairer un appareil Bluetooth » ci-dessous, puis actualisez. Pour l'USB : branchez l'imprimante et actualisez.", "No device found. For Bluetooth: turn it on if needed (a prompt may appear automatically), pair the printer via \"Pair a Bluetooth device\" below, then refresh. For USB: plug in the printer and refresh."),
        ["Printer_NoDevicesFoundWindows"] = ("Aucune imprimante trouvée. Installez d'abord le pilote de l'imprimante (USB ou Bluetooth) via « Gérer les imprimantes Windows » ci-dessous, puis actualisez.", "No printer found. Install the printer's driver (USB or Bluetooth) via \"Manage Windows printers\" below first, then refresh."),
        ["Printer_PairBluetooth"] = ("Pairer un appareil Bluetooth", "Pair a Bluetooth device"),
        ["Printer_OpenWindowsSettings"] = ("Gérer les imprimantes Windows", "Manage Windows printers"),
        ["Printer_PrintTestPage"] = ("Imprimer un ticket test", "Print a test receipt"),
        ["Printer_SetAsDefault"] = ("« {0} » est maintenant l'imprimante par défaut.", "\"{0}\" is now the default printer."),
        ["Printer_SetAsDefaultUnauthorized"] = ("« {0} » est enregistrée comme imprimante par défaut, mais l'autorisation d'accès n'a pas été accordée — elle sera redemandée à la première impression.", "\"{0}\" is saved as the default printer, but access wasn't granted — it will be requested again on the first print."),
        ["Printer_PrintingTitle"] = ("Impression", "Printing"),
        ["Printer_TestPageSent"] = ("Ticket de test envoyé.", "Test receipt sent."),
        ["Printer_TestPageLabel"] = ("Test d'impression", "Print test"),
        ["Printer_TestPageItem"] = ("Article de test", "Test item"),

        // BarcodeScannerPage
        ["Scanner_Title"] = ("Scanner un code-barres", "Scan a barcode"),
        ["Scanner_Instruction"] = ("Pointez la caméra vers un code-barres", "Point the camera at a barcode"),
        ["Scanner_PermissionTitle"] = ("Autorisation caméra requise", "Camera permission required"),
        ["Scanner_PermissionMessage"] = ("Autorisez l'accès à la caméra pour scanner les codes-barres.", "Allow camera access to scan barcodes."),

        // CashRegisterPage (Section 3.6)
        ["Shift_Title"] = ("Caisse", "Cash register"),
        ["Shift_NoOpenShift"] = ("Aucune caisse ouverte pour cet emplacement.", "No till is open for this location."),
        ["Shift_OpeningAmountLabel"] = ("MONTANT D'OUVERTURE (FOND DE CAISSE)", "OPENING AMOUNT (FLOAT)"),
        ["Shift_OpenAction"] = ("Ouvrir la caisse", "Open the till"),
        ["Shift_ActiveTitle"] = ("● Caisse ouverte", "● Till open"),
        ["Shift_OpenedInfo"] = ("Ouverte le {0} par {1}", "Opened {0} by {1}"),
        ["Shift_SalesCount"] = ("Ventes", "Sales"),
        ["Shift_TotalSales"] = ("Total des ventes", "Total sales"),
        ["Shift_ExpectedCash"] = ("Espèces attendues", "Expected cash"),
        ["Shift_CloseAction"] = ("Fermer la caisse", "Close the till"),
        ["Shift_ClosingAmountLabel"] = ("MONTANT COMPTÉ", "COUNTED AMOUNT"),
        ["Shift_NotesLabel"] = ("NOTES (FACULTATIF)", "NOTES (OPTIONAL)"),
        ["Shift_NotesPlaceholder"] = ("ex. Écart expliqué par...", "e.g. Discrepancy explained by..."),
        ["Shift_ConfirmClose"] = ("Confirmer la fermeture", "Confirm closing"),
        ["Shift_InvalidAmount"] = ("Entrez un montant valide (0 ou plus).", "Enter a valid amount (0 or more)."),
        ["Shift_ClosedTitle"] = ("Caisse fermée", "Till closed"),
        ["Shift_ClosedBalanced"] = ("Le compte est exact — aucun écart.", "The count matches — no discrepancy."),
        ["Shift_ClosedOverage"] = ("Excédent de {0} par rapport au montant attendu.", "Overage of {0} versus the expected amount."),
        ["Shift_ClosedShortage"] = ("Manque de {0} par rapport au montant attendu.", "Shortage of {0} versus the expected amount."),
        ["Shift_History"] = ("HISTORIQUE DES CAISSES", "TILL HISTORY"),
        ["Shift_NoHistory"] = ("Aucune caisse enregistrée pour le moment.", "No till sessions recorded yet."),
        ["Shift_RowOpenedBy"] = ("Ouverte par {0} · en cours", "Opened by {0} · in progress"),
        ["Shift_RowOpenedClosedBy"] = ("{0} → {1}", "{0} → {1}"),
        ["Shift_OpeningAmountShort"] = ("Ouverture", "Opening"),
        ["Shift_ClosingAmountShort"] = ("Comptage", "Counted"),
        ["Shift_DiscrepancyShort"] = ("Écart", "Discrepancy"),

        // Common (continued — pagination widget shared by several list pages)
        ["Common_LoadMore"] = ("Charger plus", "Load more"),

        // ProductCatalogPage
        ["Catalog_Filters"] = ("Filtres", "Filters"),
        ["Catalog_SearchPlaceholder"] = ("Rechercher un produit", "Search for a product"),
        ["Catalog_NoProducts"] = ("Aucun produit trouvé.", "No products found."),
        ["Catalog_StatusOutOfStock"] = ("Rupture", "Out of stock"),
        ["Catalog_StatusArchived"] = ("Archivé", "Archived"),
        ["Catalog_ExpiredOn"] = ("Expiré le {0}", "Expired on {0}"),
        ["Catalog_ExpiresOn"] = ("Exp. {0}", "Exp. {0}"),

        // ProductEditPage
        ["ProductEdit_HeaderTitle"] = ("Produit", "Product"),
        ["ProductEdit_TitleNew"] = ("Nouveau produit", "New product"),
        ["ProductEdit_TitleEdit"] = ("Modifier le produit", "Edit product"),
        ["ProductEdit_SaveNew"] = ("Créer le produit", "Create product"),
        ["ProductEdit_SaveExisting"] = ("Enregistrer", "Save"),
        ["ProductEdit_GeneralInfo"] = ("INFORMATIONS GÉNÉRALES", "GENERAL INFORMATION"),
        ["ProductEdit_NameLabel"] = ("NOM", "NAME"),
        ["ProductEdit_NamePlaceholder"] = ("ex. Article en stock", "e.g. Item in stock"),
        ["ProductEdit_BarcodeLabel"] = ("CODE-BARRES (FACULTATIF)", "BARCODE (OPTIONAL)"),
        ["ProductEdit_CategoryLabel"] = ("CATÉGORIE (FACULTATIF)", "CATEGORY (OPTIONAL)"),
        ["ProductEdit_NoCategory"] = ("Aucune catégorie", "No category"),
        ["ProductEdit_SupplierLabel"] = ("FOURNISSEUR (FACULTATIF)", "SUPPLIER (OPTIONAL)"),
        ["ProductEdit_NoSupplier"] = ("Aucun fournisseur", "No supplier"),
        ["ProductEdit_PriceAndStock"] = ("PRIX ET STOCK", "PRICE AND STOCK"),
        ["ProductEdit_PurchasePriceLabel"] = ("PRIX D'ACHAT", "PURCHASE PRICE"),
        ["ProductEdit_SalePriceLabel"] = ("PRIX DE VENTE (UNITÉ)", "SALE PRICE (UNIT)"),
        ["ProductEdit_LowStockThresholdLabel"] = ("SEUIL DE STOCK FAIBLE", "LOW STOCK THRESHOLD"),
        ["ProductEdit_TaxRateLabel"] = ("TAUX DE TVA % (FACULTATIF)", "TAX RATE % (OPTIONAL)"),
        ["ProductEdit_TaxRatePlaceholder"] = ("Taux par défaut de l'entreprise", "Business default rate"),
        ["ProductEdit_FavoriteLabel"] = ("Produit favori (accès rapide en caisse)", "Favorite product (quick access at checkout)"),
        ["ProductEdit_PackagingLevels"] = ("NIVEAUX D'EMBALLAGE", "PACKAGING LEVELS"),
        ["ProductEdit_PackagingLevelsHint"] = ("ex. Carton, Boîte, Plaquette — chaque niveau indique combien d'unités de base il contient.", "e.g. Carton, Box, Blister — each level states how many base units it contains."),
        ["ProductEdit_QuantityPlaceholder"] = ("Qté en unités de base", "Qty in base units"),
        ["ProductEdit_PriceOptionalPlaceholder"] = ("Prix (facultatif)", "Price (optional)"),
        ["ProductEdit_UnitNamePlaceholder"] = ("Nom (ex. Boîte)", "Name (e.g. Box)"),
        ["ProductEdit_ArchivedNotice"] = ("Ce produit est archivé — il n'apparaît plus dans le catalogue ni en caisse.", "This product is archived — it no longer appears in the catalog or at checkout."),
        ["ProductEdit_NameRequired"] = ("Le nom du produit est requis.", "The product name is required."),
        ["ProductEdit_InvalidPrices"] = ("Le prix d'achat et le prix de vente doivent être des nombres valides.", "Purchase price and sale price must be valid numbers."),
        ["ProductEdit_PackagingLevelQuantityRequired"] = ("Le niveau d'emballage « {0} » doit avoir une quantité positive.", "The packaging level \"{0}\" must have a positive quantity."),
        ["ProductEdit_ArchiveTitle"] = ("Archiver le produit", "Archive product"),
        ["ProductEdit_ArchiveMessage"] = ("Archiver « {0} » ? Il n'apparaîtra plus dans le catalogue ni en caisse, mais son historique de ventes et de stock est conservé.", "Archive \"{0}\"? It will no longer appear in the catalog or at checkout, but its sales and stock history is kept."),
        ["ProductEdit_Archive"] = ("Archiver", "Archive"),

        // Category prompt (shared: ProductEditPage's quick-add + CategoryManagementPage's add)
        ["Category_NewTitle"] = ("Nouvelle catégorie", "New category"),
        ["Category_NamePrompt"] = ("Nom de la catégorie", "Category name"),

        // ProductFilterPage
        ["Catalog_Filters_Title"] = ("Filtres", "Filters"),
        ["Filter_StockStatus"] = ("STATUT DE STOCK", "STOCK STATUS"),
        ["Filter_Favorites"] = ("FAVORIS", "FAVORITES"),
        ["Filter_FavoritesOnly"] = ("Favoris uniquement", "Favorites only"),
        ["Filter_Expiration"] = ("EXPIRATION", "EXPIRATION"),
        ["Filter_ExpiringSoon"] = ("Expire bientôt (≤30 jours)", "Expiring soon (≤30 days)"),
        ["Filter_AlreadyExpired"] = ("Déjà expiré", "Already expired"),
        ["Filter_ShowArchived"] = ("Afficher les produits archivés", "Show archived products"),
        ["Filter_Reset"] = ("Réinitialiser", "Reset"),
        ["Filter_Apply"] = ("Appliquer", "Apply"),

        // ArchivedProductsPage
        ["Archived_Title"] = ("Produits archivés", "Archived products"),
        ["Archived_Subtitle"] = ("Ces produits n'apparaissent plus dans le catalogue ni en caisse. Restaurez-en un pour le réactiver.", "These products no longer appear in the catalog or at checkout. Restore one to reactivate it."),
        ["Archived_NoProducts"] = ("Aucun produit archivé.", "No archived products."),

        // CategoryPickerPage
        ["CategoryPicker_Title"] = ("Choisir une catégorie", "Choose a category"),
        ["CategoryPicker_SearchPlaceholder"] = ("Rechercher une catégorie", "Search for a category"),
        ["CategoryPicker_New"] = ("Nouvelle", "New"),
        ["CategoryPicker_NoResults"] = ("Aucune catégorie trouvée.", "No categories found."),

        // PackagingUnitPickerPage
        ["UnitPicker_Title"] = ("Choisir un conditionnement", "Choose a packaging unit"),
        ["UnitPicker_SearchPlaceholder"] = ("Rechercher (ex. Boîte)", "Search (e.g. Box)"),
        ["UnitPicker_New"] = ("Nouveau", "New"),
        ["UnitPicker_NoResults"] = ("Aucun conditionnement trouvé.", "No packaging units found."),
        ["UnitPicker_NewTitle"] = ("Nouveau conditionnement", "New packaging unit"),
        ["UnitPicker_NamePrompt"] = ("Nom (ex. Boîte, Carton)", "Name (e.g. Box, Carton)"),

        // CategoryManagementPage
        ["CategoryManagement_Empty"] = ("Aucune catégorie. Utilisez le bouton + pour en créer une.", "No categories. Use the + button to create one."),
        ["CategoryManagement_DeleteTitle"] = ("Supprimer la catégorie", "Delete category"),
        ["CategoryManagement_DeleteMessage"] = ("Supprimer « {0} » ? Les produits qui l'utilisent perdront simplement leur catégorie.", "Delete \"{0}\"? Products using it will simply lose their category."),
        ["CategoryManagement_Delete"] = ("Supprimer", "Delete"),

        // StockReceivePage
        ["StockReceive_Title"] = ("Réception de stock", "Stock receipt"),
        ["StockReceive_BatchNumberLabel"] = ("NUMÉRO DE LOT", "BATCH NUMBER"),
        ["StockReceive_ExpiryLabel"] = ("DATE D'EXPIRATION", "EXPIRY DATE"),
        ["StockReceive_QuantityLabel"] = ("QUANTITÉ (EN UNITÉS DE BASE)", "QUANTITY (IN BASE UNITS)"),
        ["StockReceive_PurchasePriceLabel"] = ("PRIX D'ACHAT UNITAIRE (FACULTATIF)", "UNIT PURCHASE PRICE (OPTIONAL)"),
        ["StockReceive_PurchasePricePlaceholder"] = ("Prix catalogue par défaut", "Default catalog price"),
        ["StockReceive_Save"] = ("Réceptionner", "Receive"),
        ["StockReceive_BatchNumberRequired"] = ("Le numéro de lot est requis.", "The batch number is required."),
        ["StockReceive_InvalidQuantity"] = ("La quantité doit être un nombre entier positif.", "The quantity must be a positive whole number."),
        ["StockReceive_SavedTitle"] = ("Réception enregistrée", "Receipt saved"),
        ["StockReceive_SavedMessage"] = ("Lot « {0} » : {1} unités.", "Batch \"{0}\": {1} units."),

        // StockAdjustPage
        ["StockAdjust_Title"] = ("Ajustement de stock", "Stock adjustment"),
        ["StockAdjust_BatchLabel"] = ("LOT", "BATCH"),
        ["StockAdjust_BatchPickerTitle"] = ("Choisir un lot", "Choose a batch"),
        ["StockAdjust_DeltaLabel"] = ("VARIATION (+ OU -)", "CHANGE (+ OR -)"),
        ["StockAdjust_ReasonLabel"] = ("MOTIF", "REASON"),
        ["StockAdjust_ReasonPlaceholder"] = ("ex. Casse, péremption, vol, correction d'inventaire", "e.g. Breakage, expiry, theft, inventory correction"),
        ["StockAdjust_Save"] = ("Ajuster", "Adjust"),
        ["StockAdjust_BatchUnits"] = ("{0} — {1} unités", "{0} — {1} units"),
        ["StockAdjust_BatchExpiry"] = (" — exp. {0}", " — exp. {0}"),
        ["StockAdjust_ChooseBatch"] = ("Choisissez un lot.", "Choose a batch."),
        ["StockAdjust_InvalidDelta"] = ("La variation doit être un nombre entier différent de zéro.", "The change must be a non-zero whole number."),
        ["StockAdjust_ReasonRequired"] = ("Le motif est requis.", "The reason is required."),
        ["StockAdjust_SavedTitle"] = ("Ajustement enregistré", "Adjustment saved"),
        ["StockAdjust_SavedMessage"] = ("Lot « {0} » : nouveau solde {1} unités.", "Batch \"{0}\": new balance {1} units."),

        // SalesHistoryPage
        ["SalesHistory_Today"] = ("Aujourd'hui", "Today"),
        ["SalesHistory_Last7Days"] = ("7 jours", "7 days"),
        ["SalesHistory_Last30Days"] = ("30 jours", "30 days"),
        ["SalesHistory_All"] = ("Tout", "All"),
        ["SalesHistory_From"] = ("DU", "FROM"),
        ["SalesHistory_To"] = ("AU", "TO"),
        ["SalesHistory_NoSales"] = ("Aucune vente enregistrée.", "No sales recorded."),
        ["SalesHistory_InvalidRangeTitle"] = ("Période invalide", "Invalid date range"),
        ["SalesHistory_InvalidRangeMessage"] = ("La date de début doit précéder la date de fin.", "The start date must be before the end date."),
        ["SalesHistory_Articles"] = ("article(s)", "item(s)"),
        ["SalesHistory_Export"] = ("Exporter (Excel)", "Export (Excel)"),
        ["SalesHistory_ExportEmpty"] = ("Aucune donnée à exporter pour cette période.", "No data to export for this period."),
        ["SalesHistory_CsvDate"] = ("Date", "Date"),
        ["SalesHistory_CsvCashier"] = ("Caissier", "Cashier"),
        ["SalesHistory_CsvPayment"] = ("Paiement", "Payment"),
        ["SalesHistory_CsvItems"] = ("Articles", "Items"),
        ["SalesHistory_CsvTotal"] = ("Total", "Total"),

        // SaleDetailPage
        ["SaleDetail_Title"] = ("Détail de la vente", "Sale detail"),
        ["SaleDetail_Cashier"] = ("Caissier(e) : {0}", "Cashier: {0}"),
        ["SaleDetail_Payment"] = ("Paiement : {0}", "Payment: {0}"),
        ["SaleDetail_PaymentBreakdown"] = ("RÉPARTITION DU PAIEMENT", "PAYMENT BREAKDOWN"),
        ["SaleDetail_Tendered"] = ("Montant reçu : {0}", "Amount received: {0}"),
        ["SaleDetail_ChangeDue"] = ("Monnaie rendue : {0}", "Change given: {0}"),
        ["SaleDetail_Articles"] = ("ARTICLES", "ITEMS"),
    };
}
